### ISSUE TITLE
Updating show broken

### ISSUE THREAD

**Issue by legolasmcm** [ltguillaume/droidshows#84]
Never had an issue updating with any version I've used. Always worked for me untill the past 3 days or so. Some shows update, some don't. Not sure if anybody else is experiencing this or not.

**Comment by casperklein** [comment]
I noticed the same. I am pretty sure, that is an upstream problem of thetvdb.com. There is an option in the settings, to use a tvdb mirror. However, that suffers from the same problem.

**Comment by ltguillaume** [comment]
Saw the same thing happening yesterday. It's just a timeout, so probably capacity problems with TheTVDB.com. They've always had periods like this. Perhaps you can find some info about it on their forums.

**Comment by legolasmcm** [comment]
Appreciate your time, mate.

**Comment by ltguillaume** [comment]
Leaving this open to be revisited in a couple of days.

**Comment by legolasmcm** [comment]
I just checked this feature. It appears it has been resolved and mine got through every update and it did it in the normal amount of time.

**Comment by ltguillaume** [comment]
Great! I'll close the issue, but don't hesitate to comment here again if it happens again or if you find some relevant info about it.

**Comment by beerisgood** [comment]
@ltGuillaume 
Looks like the problem is back. Using the tvdb mirror doesn't help

I also wonder why only tvdb mirror is used, no matter if it's disabled or not.
Maybe this is the reason why updates failed?

**Comment by ltguillaume** [comment]
I don't understand what you mean. The main URL used is https://thetvdb.com. The mirror is https://thetvdb.plexapp.com.

**Comment by ltguillaume** [comment]
See https://forums.thetvdb.com/viewtopic.php?f=17&t=63137&start=20
